int a;
int b;
Console.Write("Ingrese un numero: ");
a = Convert.ToInt32(Console.ReadLine());
Console.Write("Ingrese el segundo numero: ");
b = Convert.ToInt32(Console.ReadLine());
int result = a + b;
Console.WriteLine("El resultado es: " + result);
int x;
int y;
Console.Write("Ingrese un numero para multiplicar: ");
x = Convert.ToInt32(Console.ReadLine());
Console.Write("Ingrese el segundo numero a multiplicar: ");
y = Convert.ToInt32(Console.ReadLine());
int resultx = x * y;
Console.WriteLine("El resultado de la multiplicacion es: " + resultx);